[2023-08-29T05:03:22.093+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: website_crawler.crawl_task manual__2023-08-29T04:58:10.475381+00:00 [queued]>
[2023-08-29T05:03:22.127+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: website_crawler.crawl_task manual__2023-08-29T04:58:10.475381+00:00 [queued]>
[2023-08-29T05:03:22.132+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-08-29T05:03:22.193+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): crawl_task> on 2023-08-29 04:58:10.475381+00:00
[2023-08-29T05:03:22.221+0000] {standard_task_runner.py:57} INFO - Started process 59 to run task
[2023-08-29T05:03:22.242+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'website_crawler', 'crawl_task', 'manual__2023-08-29T04:58:10.475381+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/crawl_data_using_BeautifulSoup.py', '--cfg-path', '/tmp/tmpk9l5cpqa']
[2023-08-29T05:03:22.259+0000] {standard_task_runner.py:85} INFO - Job 119: Subtask crawl_task
[2023-08-29T05:03:22.597+0000] {task_command.py:415} INFO - Running <TaskInstance: website_crawler.crawl_task manual__2023-08-29T04:58:10.475381+00:00 [running]> on host f38233847898
[2023-08-29T05:03:22.835+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='website_crawler' AIRFLOW_CTX_TASK_ID='crawl_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T04:58:10.475381+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T04:58:10.475381+00:00'
[2023-08-29T05:03:23.878+0000] {crawl_data_using_BeautifulSoup.py:40} INFO - <ul class="pagination">
<li class="disabled-page"><span>«</span></li>
<li class="active-page"><a href="/">1</a></li>
<li><a href="/posts/2">2</a></li>
<li><a href="/posts/3">3</a></li>
<li><a href="/posts/4">4</a></li>
<li><a href="/posts/5">5</a></li>
<li><a href="/posts/6">6</a></li>
<li class="disabled-page"><span>...</span></li>
<li><a href="/posts/13">13</a></li>
<li><a href="/posts/14">14</a></li>
<li><a href="/posts/2">»</a></li>
</ul>
[2023-08-29T05:03:23.888+0000] {crawl_data_using_BeautifulSoup.py:42} INFO - 11
[2023-08-29T05:03:23.906+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/crawl_data_using_BeautifulSoup.py", line 47, in crawl_section_pages
    while current_page <= num_page:
TypeError: '<=' not supported between instances of 'int' and 'str'
[2023-08-29T05:03:23.984+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=website_crawler, task_id=crawl_task, execution_date=20230829T045810, start_date=20230829T050322, end_date=20230829T050323
[2023-08-29T05:03:24.046+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 119 for task crawl_task ('<=' not supported between instances of 'int' and 'str'; 59)
[2023-08-29T05:03:24.118+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-29T05:03:24.223+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
